# -*- coding: utf-8 -*-
"""Step 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQFbQ6atDQstS1JbAfNEbwzrQUFgtz8S
"""

# STEP 2: DATA COLLECTION & UNDERSTANDING

import pandas as pd
import numpy as np

# 1. Load data
df = pd.read_csv('/content/cleaned_student_exam_wide_format - student_attributes_final_version_for_capstone.csv')

# 2. Basic dataset overview
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

# 3. Data structure
print("\nDataset info:")
df.info()

# 4. Summary statistics
print("\nSummary statistics:")
display(df.describe(include='all'))

# 5. Missing values
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

missing_report = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percent': missing_pct
})

print("\nMissing values report:")
display(missing_report[missing_report['Missing Count'] > 0])

# 6. Duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

# 7. Target distribution
print("\nLicensure Exam Result distribution:")
print(df['Licensure Exam Result'].value_counts())
print("\nLicensure Exam Result proportion:")
print(df['Licensure Exam Result'].value_counts(normalize=True))

# 8. Categorical value checks
categorical_cols = ['Gender', 'Type of Examinee']

for col in categorical_cols:
    print(f"\nValue counts for {col}:")
    print(df[col].value_counts(dropna=False))

# 9. Score range checks
score_cols = [
    col for col in df.columns
    if col not in ['Student ID', 'Gender', 'Type of Examinee', 'Licensure Exam Result']
]

range_issues = {}

for col in score_cols:
    if pd.api.types.is_numeric_dtype(df[col]):
        min_val = df[col].min(skipna=True)
        max_val = df[col].max(skipna=True)
        if col not in ['total_attempts', 'avg_attempts', 'avg_improvement', 'score_std', 'num_exams']:
            if min_val < 0 or max_val > 100:
                range_issues[col] = {'min': min_val, 'max': max_val}

print("\nPotential score range issues:")
print(range_issues if range_issues else "No obvious issues found.")

# 10. Quick numeric correlations with target
corr_with_target = df.corr(numeric_only=True)['Licensure Exam Result'].sort_values(ascending=False)

print("\nTop correlations with Licensure Exam Result:")
display(corr_with_target.head(15))

print("\nLowest correlations with Licensure Exam Result:")
display(corr_with_target.tail(15))

# 11. Simple interpretation notes
print("\nINTERPRETATION NOTES")
print("- Each row represents one student.")
print("- Target variable is binary: 0 = Fail, 1 = Pass.")
print("- Missing values in later assessments may reflect incomplete participation.")
print("- Gender needs category standardization (e.g., 'Male' vs 'male').")
print("- The dataset appears suitable for binary classification modeling.")