# -*- coding: utf-8 -*-
"""Step 3 updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11XgrDea2QMmkxdX-W2j8cK7EIgWtpObR
"""

# 0. Setup

import os
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.feature_selection import SelectKBest, chi2, RFE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA

# Make plots a bit cleaner
plt.rcParams["figure.dpi"] = 120
sns.set_theme(style="whitegrid")

# 1. Load data

file_path = "cleaned_student_exam_wide_format - student_attributes_final_version_for_capstone.csv"
df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
display(df.head())

# 2. Define target and basic column groups

target_col = "Licensure Exam Result"
id_col = "Student ID"

categorical_cols = df.select_dtypes(include="object").columns.tolist()
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
numeric_feature_cols = [col for col in numeric_cols if col != target_col]

print("Categorical columns:", categorical_cols)
print("Numeric columns:", len(numeric_cols))

# 3a. Data Cleaning

# 3a.1 Check duplicates

duplicate_rows = df.duplicated().sum()
duplicate_ids = df[id_col].duplicated().sum()

print("Duplicate rows:", duplicate_rows)
print("Duplicate Student IDs:", duplicate_ids)

# 3a.2 Missing values

missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100
}).sort_values("missing_count", ascending=False)

display(missing_summary[missing_summary["missing_count"] > 0].head(15))

# Visualization: top missing variables
top_missing = missing_summary[missing_summary["missing_count"] > 0].head(12).sort_values("missing_percent")
plt.figure(figsize=(8, 5))
plt.barh(top_missing.index, top_missing["missing_percent"])
plt.xlabel("Missing values (%)")
plt.title("Top Variables with Missing Values")
plt.tight_layout()
plt.show()

# 3a.3 Outlier inspection using IQR

outlier_records = []

for col in numeric_feature_cols:
    series = df[col].dropna()
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outlier_count = ((series < lower) | (series > upper)).sum()

    outlier_records.append({
        "variable": col,
        "outlier_count": outlier_count,
        "lower_bound": lower,
        "upper_bound": upper
    })

outlier_summary = pd.DataFrame(outlier_records).sort_values("outlier_count", ascending=False)
display(outlier_summary.head(10))

# 3b. Exploratory Data Analysis (EDA)


# 3b.1 Target distribution

target_counts = df[target_col].value_counts().sort_index()
target_labels = ["Fail", "Pass"]

plt.figure(figsize=(5, 4))
bars = plt.bar(target_labels, [target_counts.get(0, 0), target_counts.get(1, 0)])
plt.title("Licensure Exam Result Distribution")
plt.ylabel("Number of Students")

total_n = len(df)
for bar, value in zip(bars, [target_counts.get(0, 0), target_counts.get(1, 0)]):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        value + 2,
        f"{value} ({value / total_n:.1%})",
        ha="center"
    )
plt.tight_layout()
plt.show()


# 3b.2 Univariate analysis

aggregate_cols = ["avg_first_score", "avg_last_score", "avg_best_score", "total_attempts"]

fig, axes = plt.subplots(2, 2, figsize=(10, 7))
for ax, col in zip(axes.flatten(), aggregate_cols):
    ax.hist(df[col].dropna(), bins=20)
    ax.set_title(col)
    ax.set_ylabel("Count")
plt.tight_layout()
plt.show()


# 3b.3 Bivariate analysis: pass vs fail

boxplot_cols = ["avg_first_score", "avg_last_score", "avg_best_score"]

fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))
for ax, col in zip(axes, boxplot_cols):
    sns.boxplot(data=df, x=target_col, y=col, ax=ax)
    ax.set_xticklabels(["Fail", "Pass"])
    ax.set_title(f"{col} by Result")
plt.tight_layout()
plt.show()

# Group means for interpretation
group_means = df.groupby(target_col)[["avg_first_score", "avg_last_score", "avg_best_score", "total_attempts", "num_exams"]].mean().round(2)
group_means.index = ["Fail", "Pass"]
display(group_means)


# 3b.4 Relationships for categorical variables

gender_passrate = pd.crosstab(df["Gender"], df[target_col], normalize="index")
examinee_passrate = pd.crosstab(df["Type of Examinee"], df[target_col], normalize="index")

print("Pass rates by Gender")
display(gender_passrate)

print("Pass rates by Type of Examinee")
display(examinee_passrate)


# 3b.5 Correlation analysis

correlations = df[numeric_feature_cols + [target_col]].corr(numeric_only=True)[target_col].drop(target_col)
top_correlations = correlations.reindex(correlations.abs().sort_values(ascending=False).index).head(15)

plt.figure(figsize=(8, 6))
top_correlations.sort_values().plot(kind="barh")
plt.title("Top Numerical Correlations with Licensure Exam Result")
plt.xlabel("Correlation")
plt.tight_layout()
plt.show()

# Heatmap for the strongest variables
heatmap_cols = top_correlations.index.tolist()[:10] + [target_col]
plt.figure(figsize=(9, 7))
sns.heatmap(df[heatmap_cols].corr(numeric_only=True), annot=False, cmap="coolwarm", center=0)
plt.title("Correlation Heatmap of Top Predictors")
plt.tight_layout()
plt.show()

display(top_correlations)

# 3c. Feature Engineering

# Create a copy so raw data stays intact
df_fe = df.copy()

# Domain-informed engineered features
# These aim to capture engagement, learning gain, and score stability
df_fe["exam_coverage_ratio"] = df_fe["num_exams"] / 11
df_fe["best_minus_first"] = df_fe["avg_best_score"] - df_fe["avg_first_score"]
df_fe["last_minus_first"] = df_fe["avg_last_score"] - df_fe["avg_first_score"]
df_fe["best_minus_last"] = df_fe["avg_best_score"] - df_fe["avg_last_score"]
df_fe["attempt_intensity"] = df_fe["total_attempts"] / df_fe["num_exams"].replace(0, np.nan)
df_fe["stability_index"] = 1 / (1 + df_fe["score_std"])
df_fe["score_range_proxy"] = df_fe["max_best_score"] - df_fe["avg_first_score"]

engineered_cols = [
    "exam_coverage_ratio",
    "best_minus_first",
    "last_minus_first",
    "best_minus_last",
    "attempt_intensity",
    "stability_index",
    "score_range_proxy",
]

display(df_fe[engineered_cols].head())

# Quick check of engineered feature behavior by target
engineered_group_means = df_fe.groupby(target_col)[engineered_cols].mean().round(3)
engineered_group_means.index = ["Fail", "Pass"]
display(engineered_group_means)

# 3d. Feature Selection

# Exclude ID and target from X
X = df_fe.drop(columns=[id_col, target_col])
y = df_fe[target_col]

num_features = X.select_dtypes(include=[np.number]).columns.tolist()
cat_features = X.select_dtypes(exclude=[np.number]).columns.tolist()


# 3d.1 Filter method: Chi-square

# Chi-square requires non-negative values, so I use MinMaxScaler.
chi_preprocessor = ColumnTransformer(
    transformers=[
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", MinMaxScaler())
        ]), num_features),
        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore"))
        ]), cat_features)
    ]
)

X_chi = chi_preprocessor.fit_transform(X)
chi_feature_names = chi_preprocessor.get_feature_names_out()

chi_selector = SelectKBest(score_func=chi2, k=10)
chi_selector.fit(X_chi, y)

chi_scores = pd.Series(chi_selector.scores_, index=chi_feature_names).sort_values(ascending=False)
print("Top 10 Chi-square features")
display(chi_scores.head(10))


# 3d.2 Wrapper method: RFE

rfe_preprocessor = ColumnTransformer(
    transformers=[
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ]), num_features),
        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(drop="if_binary", handle_unknown="ignore"))
        ]), cat_features)
    ]
)

X_model = rfe_preprocessor.fit_transform(X)
model_feature_names = rfe_preprocessor.get_feature_names_out()

rfe_model = LogisticRegression(max_iter=3000, solver="liblinear")
rfe_selector = RFE(estimator=rfe_model, n_features_to_select=10)
rfe_selector.fit(X_model, y)

rfe_selected_features = pd.Series(rfe_selector.support_, index=model_feature_names)
rfe_selected_features = rfe_selected_features[rfe_selected_features].index.tolist()

print("RFE selected features:")
for feature in rfe_selected_features:
    print("-", feature)


# 3d.3 Embedded method: Tree-based importance

rf_model = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    class_weight="balanced"
)
rf_model.fit(X_model, y)

rf_importances = pd.Series(rf_model.feature_importances_, index=model_feature_names).sort_values(ascending=False)
print("Top 10 Random Forest feature importances")
display(rf_importances.head(10))

plt.figure(figsize=(8, 6))
rf_importances.head(10).sort_values().plot(kind="barh")
plt.title("Top 10 Random Forest Feature Importances")
plt.xlabel("Importance")
plt.tight_layout()
plt.show()

# 3e. Dimensionality Reduction (PCA)


# PCA should be done on imputed + encoded + scaled data
X_pca_input = X_model.toarray() if hasattr(X_model, "toarray") else X_model

pca = PCA()
pca.fit(X_pca_input)

explained_variance = pca.explained_variance_ratio_
cumulative_variance = np.cumsum(explained_variance)

# How many components for common thresholds?
n_components_80 = np.argmax(cumulative_variance >= 0.80) + 1
n_components_90 = np.argmax(cumulative_variance >= 0.90) + 1
n_components_95 = np.argmax(cumulative_variance >= 0.95) + 1

print("Components for 80% variance:", n_components_80)
print("Components for 90% variance:", n_components_90)
print("Components for 95% variance:", n_components_95)

# Scree / cumulative variance plot
plt.figure(figsize=(8, 5))
plt.plot(range(1, len(cumulative_variance) + 1), cumulative_variance, marker="o")
plt.axhline(0.80, linestyle="--", color="gray")
plt.axhline(0.90, linestyle="--", color="gray")
plt.axhline(0.95, linestyle="--", color="gray")
plt.xlabel("Number of Principal Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("PCA Cumulative Explained Variance")
plt.tight_layout()
plt.show()

# 2D PCA visualization
pca_2 = PCA(n_components=2)
X_pca_2 = pca_2.fit_transform(X_pca_input)

pca_df = pd.DataFrame({
    "PC1": X_pca_2[:, 0],
    "PC2": X_pca_2[:, 1],
    "Result": y.map({0: "Fail", 1: "Pass"})
})

plt.figure(figsize=(7, 5))
sns.scatterplot(data=pca_df, x="PC1", y="PC2", hue="Result", alpha=0.7)
plt.title("PCA Projection of Students")
plt.tight_layout()
plt.show()

# 4. Final Step 3 Output Summary

print("\nSTEP 3 SUMMARY")
print("1. Data cleaning documented missing values, duplicates, and IQR-based outliers.")
print("2. EDA showed that passers tend to have higher aggregate scores and broader exam coverage.")
print("3. Feature engineering added engagement, gain, and stability variables.")
print("4. Feature selection used filter, wrapper, and embedded methods.")
print("5. PCA was applied and justified as an optional dimensionality reduction branch.")

# Saved engineered dataset for Step 4
df_fe.to_csv("step3_engineered_dataset.csv", index=False)
print("\nSaved engineered dataset as: step3_engineered_dataset.csv")